### PR TITLE
Hx/sy - added filter search page

### PR DESCRIPTION
**Pull request by xempst**
Description: Added a controller method in HomePageController.java which directs user to the filter page. Added filter.html which is a clone of index.html but with Filter search as the name. Added a filter search button which calls the controller method to direct to the filter page.

Issus: https://github.com/ucsb-cs56-w20/mapache-search/issues/144
- [ ] A filter search page separated from the main page
- [ ] A button named Filter Search which directs to that filter search page

### CODE REVIEW

**Comment by maxcolbert** [comment]
looks good, simply a duplication of the original search but for filters

**Comment by pconrad** [comment]
It would help if you named your branch after your team, e.g. w-5pm-a-filteredPage or t-6pm-c-filteredPage so that we know whom to give credit for the work.  Could you at least put your team name as a comment on the PR?  Thanks!

**Comment by pconrad** [comment]
Ah, I see that I can hover over the project, and see that it's apparently `w-5pm-b`

**Comment by pconrad** [comment]
@maxcolbert It appears that there are no points listed for the PR in https://github.com/ucsb-cs56-w20/FEEDBACK-w-5pm-b/settings/access

Please update the FEEDBACK repo with the points if this team earned any.  If they didn't, there should be a notation in the FEEDBACK repo as to why.

**Pull request merged**
